---
title: "Boosting"
output: html_notebook
---

```{r}
source("2-model_tests.R")
```

## eXtreme Gradient Boosting

### Tree

```{r}
xgbGrid <- expand.grid(
    nrounds = 1000, 
    eta = c(0.01, 0.001, 0.0001), 
    max_depth = c(2, 4, 6, 8, 10), 
    gamma = 1, 
    colsample_bytree = 1, 
    min_child_weight = 1
)
```

```{r}
if (!file.exists("models/xgb_dv.Rds")) {
    set.seed(1056)
    xgb.dv <- train(
        Party ~ .,
        data = train.dv[, -1],
        method = "xgbTree",
        trControl = ctrl,
        metric = "ROC",
        tuneGrid = xgbGrid
    )
    
    saveRDS(xgb.dv, "models/xgb_dv.Rds")
} else {
    library(xgboost)
    xgb.dv <- readRDS("models/xgb_dv.Rds")
}
```

### Linear

```{r}
set.seed(123)
seeds <- vector(mode = "list", length = 11)
for(i in 1:10) seeds[[i]] <- sample.int(1000, 1000)
seeds[[11]] <- sample.int(1000, 1)
ctrl$seeds <- seeds
```


```{r}
if (!file.exists("models/xgbL_dv.Rds")) {
    set.seed(1056)
    xgbL.dv <- train(
        Party ~ .,
        data = train.dv[, -1],
        method = "xgbLinear",
        trControl = ctrl,
        metric = "ROC",
        # tuneGrid = xgbGrid
        tuneLength = 10
    )
    
    saveRDS(xgbL.dv, "models/xgbL_dv.Rds")
} else {
    library(xgboost)
    xgbL.dv <- readRDS("models/xgbL_dv.Rds")
}
```

```{r}
xgbL.dv
```

```{r}
pred.xgbL.dv <- predict(xgbL.dv, valid.dv[, -1])
confusionMatrix(pred.xgbL.dv, valid.party)
```

## Stochastic Gradient Boosting
```{r}
gbmGrid <- expand.grid(
    interaction.depth = c(1, 5, 9), # 3, 7
    n.trees = (1:10) * 100, # (1:20)
    shrinkage = 0.1, # 0.01
    n.minobsinnode = 10 # 20
)
```

```{r}

if (!file.exists("models/gbm_set.Rds")) {
    set.seed(1056)
    gbm.set <- train(
        Party ~ .,
        data = train.set[, -1],
        method = "gbm",
        trControl = ctrl,
        tuneGrid = gbmGrid,
        metric = "ROC"
    )
    
    saveRDS(gbm.set, "models/gbm_set.Rds")

} else {
    library(gbm)
    gbm.set <- readRDS("models/gbm_set.Rds")
}
```

```{r}

if (!file.exists("models/gbm_dv.Rds")) {
    set.seed(1056)
    gbm.dv <- train(
        Party ~ .,
        data = train.dv[, -1],
        method = "gbm",
        trControl = ctrl,
        tuneGrid = gbmGrid,
        metric = "ROC"
    )
    
    saveRDS(gbm.dv, "models/gbm_dv.Rds")

} else {
    library(gbm)
    gbm.dv <- readRDS("models/gbm_dv.Rds")
}
```

```{r}
xgb.dv
```

```{r}
gbm.set
```

```{r}
gbm.dv
```

```{r}
pred1 <- predict(xgb.dv, valid.dv[, -1])
pred2 <- predict(gbm.set, valid.set[, -1])
pred3 <- predict(gbm.dv, valid.dv[, -1])
```

```{r}
confusionMatrix(pred1, valid.party)
```

```{r}
confusionMatrix(pred2, valid.party)
```

```{r}
confusionMatrix(pred3, valid.party)
```
