---
title: "C5.0 Models"
output:
  html_notebook: default
---

```{r}
source("2-model_tests.R")
```

```{r}
c50Grid <- expand.grid(
    .winnow = c(TRUE, FALSE),
    .trials = c(1:9, 1:10 * 10),
    .model = c("tree", "rules")
)
```

```{r}
if (!file.exists("models/c50_data.Rds")) {
    set.seed(1056)
    c50.data <- train(
        Party ~ .,
        data = train.data[, -1],
        method = "C5.0",
        trControl = ctrl,
        na.action = na.pass,
        metric = "ROC",
        tuneGrid = c50Grid
    )

    saveRDS(c50.data, "models/c50_data.Rds")

} else {
    library(C50)
    c50.data <- readRDS("models/c50_data.Rds")
}
```

```{r}
if (!file.exists("models/c50_set.Rds")) {
    set.seed(1056)
    c50.set <- train(
        Party ~ .,
        data = train.set[, -1],
        method = "C5.0",
        trControl = ctrl,
        # na.action = na.pass,
        metric = "ROC",
        tuneGrid = c50Grid
    )
    
    saveRDS(c50.set, "models/c50_set.Rds")

} else {
    library(C50)
    c50.set <- readRDS("models/c50_set.Rds")
}
```

```{r}
if (!file.exists("models/c50_dv.Rds")) {
    set.seed(1056)
    c50.dv <- train(
        Party ~ .,
        data = train.dv[, -1],
        method = "C5.0",
        trControl = ctrl,
        # na.action = na.pass,
        metric = "ROC",
        tuneGrid = c50Grid
    )
    
    saveRDS(c50.dv, "models/c50_dv.Rds")

} else {
    library(C50)
    c50.dv <- readRDS("models/c50_dv.Rds")
}
```

```{r}
c50.data
```

```{r}
c50.set
```

```{r}
c50.dv
```

```{r}
pred1 <- predict(c50.data, valid.data[, -c(1, 7)], na.action = na.pass)
pred2 <- predict(c50.set, valid.set[, -1])
pred3 <- predict(c50.dv, valid.dv[, -1])
```

```{r}
confusionMatrix(pred1, valid.party)
```

```{r}
confusionMatrix(pred2, valid.party)
```

```{r}
confusionMatrix(pred3, valid.party)
```

```{r}
vi1 <- varImp(c50.data)
plot(vi1, top = 20)
```

```{r}
vi2 <- varImp(c50.set)
plot(vi2, top = 20)
```

```{r}
vi3 <-varImp(c50.dv)
plot(vi3, top = 20)
```

```{r}
c50.vi1 <- data_frame(vars = rownames(vi1$importance), vi1 = vi1$importance$Overall) %>%
    mutate(var.name = str_replace_all(vars, "([0-9]{5,6}).*", "\\1"),
           var.name = str_replace_all(var.name, ".*HouseholdStatus.*", "HouseholdStatus"),
           var.name = str_replace_all(var.name, ".*EducationLevel.*", "EducationLevel"),
           var.name = str_replace_all(var.name, ".*Income.*", "Income"),
           var.name = str_replace_all(var.name, ".*Gender.*", "Gender")) %>%
    group_by(var.name) %>%
    summarize(vi1 = max(vi1))

c50.vi2 <- data_frame(vars = rownames(vi2$importance), vi2 = vi2$importance$Overall) %>%
    mutate(var.name = str_replace_all(vars, "([0-9]{5,6}).*", "\\1"),
           var.name = str_replace_all(var.name, ".*HouseholdStatus.*", "HouseholdStatus"),
           var.name = str_replace_all(var.name, ".*EducationLevel.*", "EducationLevel"),
           var.name = str_replace_all(var.name, ".*Income.*", "Income"),
           var.name = str_replace_all(var.name, ".*Gender.*", "Gender")) %>%
    group_by(var.name) %>%
    summarize(vi2 = max(vi2))

c50.vi3 <- data_frame(vars = rownames(vi3$importance), vi3 = vi3$importance$Overall) %>%
    mutate(var.name = str_replace_all(vars, "\\..*", ""),
           var.name = str_replace_all(var.name, "\\`", "")) %>%
    group_by(var.name) %>%
    summarize(vi3 = max(vi3))

c50.vi <- inner_join(c50.vi1, c50.vi2, by = "var.name") %>%
    inner_join(c50.vi3, by = "var.name")
```

```{r}
keep <- filter(c50.vi, vi1 > 0 | vi2 > 0 | vi3 > 0)
keep
```

```{r}
library(tidyr)

perf <- rbind(
    getTrainPerf(c50.data), 
    getTrainPerf(c50.set), 
    getTrainPerf(c50.dv)
)

perf <- mutate(perf, set = c("data", "set", "dv")) %>%
    unite(method, method, set) %>%
    # group_by(method) %>%
    gather(measure, val, -method)

ggplot(perf, aes(x = method, y = val, color = measure)) +
    geom_point()
```
