---
title: "Feature Selection Models"
output: html_notebook
---

```{r}
source("2-model_tests.R")
```

## Feature Selection

```{r}
rfeCtrl <- rfeControl(
    functions = rfFuncs,
    method = "cv",
    seeds = seeds
)
```

```{r}
subsets <- c(1:5, 10, 15, 20, 25)
```

```{r}
set.seed(1056)
rfProfile <- rfe(
    x = train.dv[, -c(1, 331)],
    y = train.party,
    sizes = subsets,
    rfeControl = rfeCtrl
)
```

```{r}
rfProfile
```

```{r}
predictors(rfProfile)
```

```{r}
ldaCtrl <- rfeControl(
    functions = ldaFuncs,
    method = "cv",
    seeds = seeds,
    index = createFolds(train.party, 10, TRUE, TRUE)
)
```

```{r}

# lc <- findLinearCombos(train.dv[, -c(hc.dv, 331)])

set.seed(1056)
ldaProfile <- rfe(
    x = train.dv[, -c(1, 331)],
    y = train.party,
    sizes = subsets,
    rfeControl = ldaCtrl
)
```

```{r}
ldaProfile
```

```{r}
predictors(ldaProfile)
```

```{r}
keep <- c("HouseholdStatus", "Q109244", "Q115611", "Q113181", "Q98197")

train.rfe <- select(train.set, HouseholdStatus, Q109244, Q115611, Q113181, Q98197)
valid.rfe <- select(valid.set, HouseholdStatus, Q109244, Q115611, Q113181, Q98197)

rfe.dv <- dummyVars(~ ., data = train.rfe)
train.rfe.dv <- predict(rfe.dv, newdata = train.rfe) %>% 
    as_data_frame() %>%
    mutate(Party = train.party)

valid.rfe.dv <- predict(rfe.dv, newdata = valid.rfe) %>%
    as_data_frame()
```

```{r}
hcor.rfe <- cor(train.rfe.dv[, -20])
hc.rfe <- findCorrelation(hcor.rfe)
```

## Partial Least Squares

```{r}
plsGrid <- expand.grid(.ncomp = 1:10)
```

```{r}
if (!file.exists("models/pls_rfe.Rds")) {
    set.seed(1056)
    pls.rfe <- train(
        Party ~ .,
        data = train.rfe.dv,
        method = "pls",
        trControl = ctrl,
        metric = "ROC",
        tuneGrid = plsGrid
    )
    
    saveRDS(pls.rfe, "models/pls_rfe.Rds")

} else {
    library(pls)
    pls.rfe <- readRDS("models/pls_rfe.Rds")
}
```

```{r}
pls.rfe
```

```{r}
pred1 <- predict(pls.rfe, valid.rfe.dv)
```

```{r}
confusionMatrix(pred1, valid.party)
```

## SVM

```{r}
fiveStats <- function(...) c(twoClassSummary(...), defaultSummary(...))

varSeq <- seq(1, ncol(train.dv) - 3, by = 2)
```


```{r}
svmFuncs <- caretFuncs
svmFuncs$summary <- fiveStats

ctrl <- rfeControl(
    method = "repeatedcv",
    repeats = 5,
    verbose = TRUE,
    functions = svmFuncs,
    index = createMultiFolds(train.party)
)

set.seed(1056)
svm.rfe <- rfe(
    x = train.dv[, -c(1, 331)],
    y = train.party,
    sizes = varSeq,
    metric = "ROC",
    rfeControl = ctrl,
    method = "svmRadial",
    tuneLength = 12,
    preProcess = c("center", "scale"),
    trControl = trainControl(method = "cv", verboseIter = FALSE, classProbs = TRUE)
)
```

```{r}
saveRDS(svm.rfe, "models/svm_rfe.Rds")
```


```{r}
if (!file.exists("models/svm_rfe.Rds")) {
    set.seed(1056)
    svm.rfe <- train(
        Party ~ .,
        data = train.rfe.dv,
        method = "svmRadial",
        trControl = ctrl,
        tuneGrid = svmGrid,
        metric = "ROC",
        preProcess = c("center", "scale")
    )
    
    saveRDS(svm.rfe, "models/svm_rfe.Rds")

} else {
    library(kernlab)
    svm.rfe <- readRDS("models/svm_rfe.Rds")
}
```

```{r}
svm.rfe
```

```{r}
pred2 <- predict(svm.rfe, valid.rfe.dv)
```

```{r}
confusionMatrix(pred2, valid.party)
```

## Neural Network

```{r}
nnetGrid <- expand.grid(.size = 1:10, .decay = c(0, 0.1, 1, 2))
maxSize <- max(nnetGrid$.size)
numWts <- 1 * (maxSize * (length(train.rfe.dv[, -20]) + 1) + maxSize + 1)
```

```{r}
if (!file.exists("models/nnet_rfe.Rds")) {
    set.seed(1056)
    nnet.rfe <- train(
        Party ~ .,
        data = train.rfe.dv,
        method = "nnet",
        trControl = ctrl,
        tuneGrid = nnetGrid,
        metric = "ROC",
        preProcess = c("center", "scale", "spatialSign"),
        trace = FALSE,
        maxit = 2000,
        MaxNWts = numWts
    )
    
    saveRDS(nnet.rfe, "models/nnet_rfe.Rds")

} else {
    library(kernlab)
    nnet.rfe <- readRDS("models/nnet_rfe.Rds")
}

```

```{r}
nnet.rfe
```

```{r}
pred3 <- predict(nnet.rfe, valid.rfe.dv)
```

```{r}
confusionMatrix(pred3, valid.party)
```
