---
title: "Feature Selection Filter"
output: html_notebook
---

```{r}
source("2-model_tests.R")
```

```{r}
pScore <- function(x, y) {
    numX <- length(unique(x))
    if (numX > 2) {
        out <- t.test(x ~ y)$p.value
    } else {
        out <- fisher.test(factor(x), y)$p.value
    }
    out
}
```

```{r}
scores <- apply(X = train.data.n[, -c(1, 7)], MARGIN = 2, FUN = pScore, y = train.data.n$Party)
```

```{r}
scores2 <- apply(X = train.dv[, -c(1, 331)], MARGIN = 2, FUN = pScore, y = train.dv$Party)
```

```{r}
pval <- sort(scores[scores < 0.05])
```

```{r}
names(pval)
```

```{r}
pval.dv <- dummyVars()
```



```{r}
pval.dv <- sort(scores2[scores2 < 0.05])
```

```{r}
names(pval.dv)
```

```{r}
hcor.fltr.dv <- cor(train.dv[, names(pval.dv)], use = "na.or.complete")
hc.fltr.dv <- findCorrelation(hcor.fltr.dv)
```

```{r}
set.seed(1056)
pls.pval.dv <- train(
    # Party ~ .,
    # data = train.dv[, -1],
    x = train.dv[, names(pval.dv)],
    y = train.party,
    method = "pls",
    trControl = trCtrl,
    metric = "ROC",
    tuneGrid = expand.grid(.ncomp = 1:10),
    preProcess = c("center", "scale")
)
```

```{r}
pls.pval.dv <- readRDS("models/pls_pval_dv.Rds")
```

```{r}
pred1 <- predict(pls.pval.dv, valid.dv[, names(pval.dv)])
confusionMatrix(pred1, valid.party)
```

```{r}
set.seed(1056)
pls.pval.dv.pca <- train(
    # Party ~ .,
    # data = train.dv[, -1],
    x = train.set[, names(pval)],
    y = train.party,
    method = "pls",
    trControl = trCtrl,
    metric = "ROC",
    tuneGrid = expand.grid(.ncomp = 1:10),
    preProcess = "pca"
)

```


```{r}
c50Grid <- expand.grid(
    .winnow = c(TRUE, FALSE),
    # .trials = c(1:9, 1:10 * 10),
    .trials = seq.int(2, 20, by = 2),
    .model = c("tree", "rules")
)
```

```{r}
train.pval <- train.data[, names(pval)]
train.pval$Party <- train.party
```

```{r}
set.seed(1056)
c50.pval.dv <- train(
    x = train.dv[, names(pval.dv)],
    y = train.party,
    # Party ~ .,
    # data = train.pval,
    method = "C5.0",
    trControl = trCtrl,
    # na.action = na.pass,
    metric = "ROC",
    tuneGrid = c50Grid
)
```

```{r}
c50.pval.dv <- readRDS("models/c50_pval_dv.Rds")
```

```{r}
pred2 <- predict(c50.pval.dv, valid.dv[, names(pval.dv)])
confusionMatrix(pred2, valid.party)
```



```{r}
library(caretEnsemble)
```

```{r}
resamps <- resamples(list(pls = pls.pval.dv, c50 = c50.pval.dv, rngr = rngr.pval.dv))
modelCor(resamps, metric = "ROC")
```

```{r}
cms.pls <- caretModelSpec(method = "pls", tuneGrid = expand.grid(.ncomp = 2))
cms.c50 <- caretModelSpec(method = "C5.0", tuneGrid = expand.grid(.winnow = FALSE, .trials = 10, .model = "tree"))
cms.rngr <- caretModelSpec(method = "ranger", tuneGrid = data.frame(mtry = 5))
set.seed(1056)
cl.pls.c50 <- caretList(
    # Party ~ .,
    # data = train.dv[, -1],
    x = train.dv[, names(pval.dv)],
    y = train.party,
    trControl = trCtrl,
    metric = "ROC",
    tuneList = list(pls = cms.pls, C5.0 = cms.c50, ranger = cms.rngr)
)
```

```{r}
saveRDS(cl.pls.c50, "models/cl_pls_c50_rngr.Rds")
```


```{r}
cs <- caretStack(cl.pls.c50, method = "glm")
cs
```

```{r}
ce <- caretEnsemble(cl.pls.c50)
ce
```

```{r}
pred.cs <- predict(cs, valid.dv[, names(pval.dv)])
pred.ce <- predict(ce, valid.dv[, names(pval.dv)])
```


```{r}
cor(as.numeric(pred.cs), as.numeric(pred.ce))
```

```{r}
confusionMatrix(pred.cs, valid.party)
```



```{r}
rfGrid <- data.frame(mtry = round(seq(5, ncol(train.dv[, names(pval.dv)]), length.out = 5)))
```

```{r}
set.seed(1056)
rngr.pval.dv <- train(
    # Party ~ .,
    # data = train.pval,
    x = train.dv[, names(pval.dv)],
    y = train.party,
    method = "ranger",
    trControl = trCtrl,
    tuneGrid = rfGrid,
    metric = "ROC",
    num.trees = 1000,
    importance = "impurity"
)
```

```{r}
saveRDS(rngr.pval.dv, "models/ranger_pval_dv.Rds")
```

```{r}
rngr.pval.dv
```


```{r}
pred2 <- predict(rngr.pval.set, valid.set[, names(pval)])
```

```{r}
confusionMatrix(pred2, valid.party)
```

```{r}
fiveStats <- function(...) c(twoClassSummary(...), defaultSummary(...))
```

```{r}
pCorrection <- function(score, x, y) {
    score <- p.adjust(score, "bonferroni")
}
```

```{r}
lda.pval <- treebagSBF
lda.pval$score <- pScore
lda.pval$summary <- fiveStats
lda.pval$filter <- pCorrection
```

```{r}
sbfCtrl <- sbfControl(
    method = "repeatedcv",
    repeats = 5,
    verbose = TRUE,
    functions = lda.pval,
    index = createMultiFolds(train.party)
)
```

```{r}
train.lgl <- train.dv %>%
    mutate_each(funs(as.logical), -USER_ID, -YOB, -Party)
```

```{r}
lda.filter <- sbf(
    # x = train.dv[, -c(1, 331)],
    # y = train.party,
    Party ~ .,
    data = train.data[, -1],
    # tol = 1.0e-12,
    sbfControl = sbfCtrl,
    na.action = na.pass
)
```

```{r}
lda.filter
```

```{r}
pred3 <- predict(lda.filter, valid.dv[, -c(1, 131)])
```

```{r}
confusionMatrix(pred3, valid.party)
```

