---
title: "Linear Classification Models"
output: html_notebook
---

```{r}
source("2-model_tests.R")
```

## Linear Discriminant Analysis

### PCA

```{r}
if (!file.exists("models/lda_pca.Rds")) {
    set.seed(1056)
    lda.pca <- train(
        Party ~ .,
        data = train.dv[, -1],
        method = "lda",
        trControl = trCtrl,
        metric = "ROC",
        preProcess = c("nzv", "pca")
    )
    
    saveRDS(lda.pca, "models/lda_pca.Rds")

} else {
    lda.pca <- readRDS("models/lda_pca.Rds")
}
```

```{r}
lda.pca
```

```{r}
pred.lda.pca <- predict(lda.pca, valid.dv[, -1])
confusionMatrix(pred.lda.pca, valid.party)
```

### ICA

```{r}
if (!file.exists("models/lda_ica.Rds")) {
    set.seed(1056)
    lda.ica <- train(
        Party ~ .,
        data = train.dv[, -1],
        method = "lda",
        trControl = trCtrl,
        metric = "ROC",
        preProcess = c("nzv", "ica")
    )
    
    saveRDS(lda.ica, "models/lda_ica.Rds")

} else {
    lda.ica <- readRDS("models/lda_ica.Rds")
}
```

```{r}
lda.ica
```

```{r}
pred.lda.ica <- predict(lda.ica, valid.dv[, -1])
confusionMatrix(pred.lda.ica, valid.party)
```

### MCA

```{r}
if (!file.exists("models/lda_mca.Rds")) {
    set.seed(1056)
    lda.mca <- train(
        Party ~ .,
        data = train.mca[, -1],
        method = "lda",
        trControl = trCtrl,
        metric = "ROC",
        preProcess = c("center", "scale")
    )
    
    saveRDS(lda.mca, "models/lda_mca.Rds")

} else {
    lda.mca <- readRDS("models/lda_mca.Rds")
}
```

```{r}
lda.mca
```

```{r}
pred.lda.mca <- predict(lda.mca, valid.mca)
confusionMatrix(pred.lda.mca, valid.party)
```

## Partial Least Squares

```{r}
plsGrid <- expand.grid(.ncomp = 1:10)
```

```{r}
if (!file.exists("models/pls_dv.Rds")) {
    set.seed(1056)
    pls.dv <- train(
        Party ~ .,
        data = train.pca[, -1],
        # data = train.dv[, -c(1, hc.dv)],
        # x = train.data[, names(pval)],
        # y = train.data$Party,
        method = "pls",
        trControl = trCtrl,
        metric = "ROC",
        tuneGrid = plsGrid,
        preProcess = c("center", "scale")
    )
    
    saveRDS(pls.dv, "models/pls_dv.Rds")

} else {
    library(pls)
    pls.dv <- readRDS("models/pls_dv.Rds")
}
```

```{r}
pls.dv
```

```{r}
# pred.pls.dv <- predict(pls.dv, valid.dv[, -c(1, hc.dv)])
# pred.pls.dv <- predict(pls.dv, valid.data[, -c(1, 338)])
# pred.pls.dv <- predict(pls.dv, valid.data[, names(pval)])
pred.pls.dv <- predict(pls.dv, valid.pca)
confusionMatrix(pred.pls.dv, valid.data$Party)
```

### PCA

```{r}
if (!file.exists("models/pls_dv_pca.Rds")) {
    set.seed(1056)
    pls.dv.pca <- train(
        Party ~ .,
        data = train.dv[, -c(1, hc.dv)],
        method = "pls",
        trControl = trCtrl,
        metric = "ROC",
        tuneGrid = plsGrid,
        preProcess = c("nzv", "pca")
    )
    
    saveRDS(pls.dv.pca, "models/pls_dv_pca.Rds")

} else {
    library(pls)
    pls.dv.pca <- readRDS("models/pls_dv_pca.Rds")
}
```

```{r}
pls.dv.pca
```

```{r}
pred.pls.dv.pca <- predict(pls.dv.pca, valid.dv[, -c(1, hc.dv)])
confusionMatrix(pred.pls.dv.pca, valid.party)
```

### Kernal PLS

```{r}
if (!file.exists("models/kpls_dv.Rds")) {
    set.seed(1056)
    kpls.dv <- train(
        Party ~ .,
        data = train.dv[, -c(1, hc.dv)],
        method = "kernelpls",
        trControl = trCtrl,
        metric = "ROC",
        tuneGrid = plsGrid,
        preProcess = c("center", "scale")
    )
    saveRDS(kpls.dv, "models/kpls_dv.Rds")
    
} else {
    library(pls)
    kpls.dv <- readRDS("models/kpls_dv.Rds")
}
```

```{r}
kpls.dv
```

```{r}
pred.kpls.dv <- predict(kpls.dv, valid.dv[, -c(1, hc.dv)])
confusionMatrix(pred.kpls.dv, valid.party)
```

## Penalized Models

```{r}
glmnGrid <- expand.grid(
    .alpha = c(0, 0.1, 0.2, 0.4, 0.6, 0.8, 1), 
    .lambda = seq(0.1, 0.2, length = 40)
)
```

```{r}
if (!file.exists("models/glmnet_dv.Rds")) {
    set.seed(1056)
    glmnet.dv <- train(
        # Party ~ .,
        # data = train.dv[, -c(1, hc.dv)],
        x = train.data[, names(pval)],
        y = train.data$Party,
        method = "glmnet",
        trControl = trCtrl,
        metric = "ROC",
        tuneGrid = glmnGrid,
        preProcess = c("nzv", "center", "scale")
    )
    
    saveRDS(glmnet.dv, "models/glmnet_dv.Rds")

} else {
    library(glmnet)
    glmnet.dv <- readRDS("models/glmnet_dv.Rds")
}
```

```{r}
glmnet.dv
```

```{r}
# pred.glmnet.dv <- predict(glmnet.dv, valid.dv[, -c(1, hc.dv)])
pred.glmnet.dv <- predict(glmnet.dv, valid.data[, names(pval)])
confusionMatrix(pred.glmnet.dv, valid.data$Party)
```

### PCA

```{r}
if (!file.exists("models/glmnet_dv_pca.Rds")) {
    set.seed(1056)
    glmnet.dv.pca <- train(
        Party ~ .,
        data = train.dv[, -c(1, hc.dv)],
        method = "glmnet",
        trControl = trCtrl,
        metric = "ROC",
        tuneGrid = expand.grid(.alpha = 0.1, .lambda = 0.1),
        preProcess = c("nzv", "pca")
    )
    
    saveRDS(glmnet.dv.pca, "models/glmnet_dv_pca.Rds")

} else {
    library(glmnet)
    glmnet.dv.pca <- readRDS("models/glmnet_dv_pca.Rds")
}
```

```{r}
glmnet.dv.pca
```

```{r}
pred.glmnet.dv.pca <- predict(glmnet.dv.pca, valid.dv[, -c(1, hc.dv)])
confusionMatrix(pred.glmnet.dv.pca, valid.party)
```

```{r}
varImp(glmnet.dv.pca)
```

### MCA

```{r}
if (!file.exists("models/glmnet_mca.Rds")) {
    set.seed(1056)
    glmnet.mca <- train(
        Party ~ .,
        # data = train.dv[, -1],
        data = train.mca[, -1],
        method = "glmnet",
        trControl = trCtrl,
        metric = "ROC",
        tuneGrid = expand.grid(.alpha = 0.1, .lambda = 0.0044944)
    )
    
    saveRDS(glmnet.mca, "models/glmnet_mca.Rds")

} else {
    library(glmnet)
    glmnet.mca <- readRDS("models/glmnet_mca.Rds")
}
```

```{r}
glmnet.mca
```

```{r}
pred.glmnet.mca <- predict(glmnet.mca, valid.mca)
confusionMatrix(pred.glmnet.mca, valid.party)
```

```{r}
varImp(glmnet.mca)
```

## Nearest Shrunken Centroids

```{r}
nscGrid <- data.frame(.threshold = 0:25)
```

```{r}
if (!file.exists("models/nsc_dv.Rds")) {
    set.seed(1056)
    nsc.dv <- train(
        # Party ~ .,
        # data = train.dv[, -1],
        x = train.data[, names(pval)],
        y = train.data$Party,
        method = "pam",
        trControl = trCtrl,
        metric = "ROC",
        tuneGrid = nscGrid,
        preProcess = "nzv"
    )
    
    saveRDS(nsc.dv, "models/nsc_dv.Rds")

} else {
    library(pamr)
    nsc.dv <- readRDS("models/nsc_dv.Rds")
}
```

```{r}
nsc.dv
```

```{r}
# pred.nsc <- predict(nsc.dv, valid.dv[, -1])
pred.nsc <- predict(nsc.dv, valid.data[, names(pval)])
confusionMatrix(pred.nsc, valid.data$Party)
```

### MCA

```{r}
if (!file.exists("models/nsc_mca.Rds")) {
    set.seed(1056)
    nsc.mca <- train(
        Party ~ .,
        data = train.mca[, -1],
        method = "pam",
        trControl = trCtrl,
        metric = "ROC",
        tuneGrid = nscGrid
        # preProcess = c("center", "scale")
    )
    
    saveRDS(nsc.mca, "models/nsc_mca.Rds")

} else {
    library(nsc)
    nsc.mca <- readRDS("models/nsc_mca.Rds")
}
```

```{r}
nsc.mca
```

```{r}
pred.nsc.mca <- predict(nsc.mca, valid.mca)
confusionMatrix(pred.nsc.mca, valid.party)
```

## Logistic Regression

```{r}
if (!file.exists("models/glm.Rds")) {
    set.seed(1056)
    mod.glm <- train(
        Party ~ .,
        data = train.pca[, -1],
        # data = train.data[, -1],
        # data = train.data[, -c(1, hc)],
        # x = train.data[, names(pval)],
        # y = train.data$Party,
        method = "glm",
        trControl = trCtrl,
        metric = "ROC",
        # tuneLength = 10,
        # tuneGrid = nscGrid,
        preProcess = c("center", "scale")
    )
    
    saveRDS(mod.glm, "models/glm.Rds")

} else {
    mod.glm <- readRDS("models/glm.Rds")
}
```

```{r}
# pred.glm <- predict(mod.glm, valid.data[, -1])
# pred.glm <- predict(mod.glm, valid.data[, names(pval)])
pred.glm <- predict(mod.glm, valid.pca[, -1])
confusionMatrix(pred.glm, valid.data$Party)
```

## Binary Discriminant Analysis

```{r}
# nscGrid <- data.frame(.threshold = 0:25)
```

```{r}
if (!file.exists("models/binda.Rds")) {
    set.seed(1056)
    binda <- train(
        # Party ~ .,
        # data = train.data[, -c(1, hc, 334:337)],
        x = train.data[, names(pval)],
        y = train.data$Party,
        method = "binda",
        trControl = trCtrl,
        metric = "ROC",
        tuneLength = 10,
        # tuneGrid = nscGrid,
        preProcess = "nzv"
    )
    
    saveRDS(binda, "models/binda.Rds")

} else {
    library(binda)
    binda <- readRDS("models/binda.Rds")
}
```

```{r}
binda
```

```{r}
# pred.binda <- predict(binda, valid.data[, -c(1, hc, 334:338)])
pred.binda <- predict(binda, valid.data[, names(pval)])
confusionMatrix(pred.binda, valid.data$Party)
```


## Compare Models

```{r}
compare_models(lda.mca, glmnet.mca)
```

```{r}
resamps <- resamples(list(lda.pca = lda.pca, 
                          # lda.mca = lda.mca, 
                          pls = pls.dv,
                          # pls.pca = pls.dv.pca,
                          # glmnet.dv = glmnet.dv, 
                          # glmnet.pca = glmnet.dv.pca,
                          glmnet.mca = glmnet.mca, 
                          nsc.dv = nsc.dv))
modelCor(resamps, metric = "ROC")
```

```{r}
resamps <- resamples(list(glm = mod.glm, 
                          pls = pls.dv,
                          binda = binda,
                          glmnet = glmnet.dv,
                          nsc = nsc.dv))
modelCor(resamps, metric = "ROC")
```


## Linear Model Averaging

```{r}
# valid.avg <- data_frame(lda = pred.lda.pca,
#                         pls = pred.pls.dv,
#                         glmnet = pred.glmnet.mca,
#                         nsc = pred.nsc)

valid.avg <- data_frame(glm = pred.glm,
                        pls = pred.pls.dv,
                        binda = pred.binda,
                        glmnet = pred.glmnet.dv,
                        nsc = pred.nsc)

linear.mod.avg <- train(
    x = valid.avg,
    y = valid.data$Party, 
    method = "rf"
)

pred.avg.valid <- predict(linear.mod.avg, valid.avg)
confusionMatrix(pred.avg.valid, valid.data$Party)
```

```{r}
linear.mod.avg
```

## Test Set Submission

```{r}
pred.test.lda <- predict(lda.pca, test.dv[, -1])
pred.test.pls <- predict(pls.dv, test.dv[, -c(1, hc.dv)])
pred.test.glmnet <- predict(glmnet.mca, test.mca)
pred.test.nsc <- predict(nsc.dv, test.dv[, -1])

test.avg <- data_frame(lda = pred.test.lda,
                       pls = pred.test.pls,
                       glmnet = pred.test.glmnet,
                       nsc = pred.test.nsc)

pred.linear.test <- predict(linear.mod.avg, test.avg)
test_submission(pred.linear.test)
```

```{r}
pred.test.glm <- predict(mod.glm, test.data[, names(pval)])
pred.test.pls <- predict(pls.dv, test.data[, names(pval)])
pred.test.glmnet <- predict(glmnet.dv, test.data[, names(pval)])
pred.test.nsc <- predict(nsc.dv, test.data[, names(pval)])
pred.test.binda <- predict(binda, test.data[, names(pval)])

test.avg <- data_frame(glm = pred.test.glm,
                        pls = pred.test.pls,
                        binda = pred.test.binda,
                        glmnet = pred.test.glmnet,
                        nsc = pred.test.nsc)

pred.linear.test <- predict(linear.mod.avg, test.avg)
test_submission(pred.linear.test)
```
