---
title: "Nonlinear Classification Models"
output: html_notebook
---

```{r}
source("2-model_tests.R")
```

## MARS

```{r}
marsGrid <- expand.grid(.degree = 1:2, .nprune = 2:38)
```

```{r}
if (!file.exists("models/mars_dv.Rds")) {
    set.seed(1056)
    mars.dv <- train(
        Party ~ .,
        data = train.dv[, -1],
        method = "earth",
        trControl = ctrl,
        tuneGrid = marsGrid,
        metric = "ROC"
    )
    
    saveRDS(mars.dv, "models/mars_dv.Rds")

} else {
    library(earth)
    mars.dv <- readRDS("models/mars_dv.Rds")
}
```

```{r}
mars.dv
```

```{r}
varImp(mars.dv)
```

```{r}
pred1 <- predict(mars.dv, valid.dv[, -1])
```

```{r}
confusionMatrix(pred1, valid.party)
```

## SVM

```{r}
library(kernlab)
svmGrid <- expand.grid(
    .sigma = sigest(as.matrix(train.dv[, -c(1, 331)])), 
    .C = 2^(seq(-4, 4))
)
```

```{r}
if (!file.exists("models/svm_dv.Rds")) {
    set.seed(1056)
    svm.dv <- train(
        Party ~ .,
        data = train.dv[, -1],
        method = "svmRadial",
        trControl = ctrl,
        tuneGrid = svmGrid,
        metric = "ROC",
        preProcess = c("center", "scale")
    )
    
    saveRDS(svm.dv, "models/svm_dv.Rds")

} else {
    library(kernlab)
    svm.dv <- readRDS("models/svm_dv.Rds")
}
```

The final values used for the model were sigma = 0.002439976 and C = 0.5. 

## Neural Network

```{r}
nnetGrid <- expand.grid(.size = 1:10, .decay = c(0, 0.1, 1, 2))
maxSize <- max(nnetGrid$.size)
numWts <- 1 * (maxSize * (length(train.dv[, -c(1, 331)]) + 1) + maxSize + 1)
```

```{r}
if (!file.exists("models/nnet_dv.Rds")) {
    set.seed(1056)
    nnet.dv <- train(
        Party ~ .,
        data = train.dv[, -1],
        method = "nnet",
        trControl = ctrl,
        tuneGrid = nnetGrid,
        metric = "ROC",
        preProcess = c("center", "scale", "spatialSign"),
        trace = FALSE,
        maxit = 2000,
        MaxNWts = numWts
    )
    
    saveRDS(nnet.dv, "models/nnet_dv.Rds")

} else {
    library(kernlab)
    nnet.dv <- readRDS("models/nnet_dv.Rds")
}
```

