---
title: "Random Forest"
output: html_notebook
---

```{r}
source("2-model_tests.R")
```

## Random Forest

### Grouped Categorical Data
```{r}
d <- train.set
rfGrid <- data.frame(mtry = c(2:9, seq(10, ncol(d) - 2, length.out = 5)))
```

```{r}
if (!file.exists("models/rf_set.Rds")) {
    set.seed(1056)
    rf.set <- train(
        Party ~ .,
        data = train.set[, -1],
        method = "rf",
        trControl = ctrl,
        tuneGrid = rfGrid,
        metric = "ROC",
        ntree = 1500,
        importance = TRUE
    )
    
    saveRDS(rf.set, "models/rf_set.Rds")

} else {
    library(randomForest)
    rf.set <- readRDS("models/rf_set.Rds")
}
```

```{r}
rf.set
```

```{r}
pred.rf.set <- predict(rf.set, valid.set[, -1])
confusionMatrix(pred.rf.set, valid.party)
```

```{r}
vi1 <- varImp(rf.set)
plot(vi1, top = 30)
```

### Independent Categorical Data

```{r}
d <- train.dv
rfGrid <- data.frame(mtry = c(2:9, seq(10, ncol(d) - 2, length.out = 5)))
```

```{r}
if (!file.exists("models/rf_dv.Rds")) {
    set.seed(1056)
    rf.dv <- train(
        Party ~ .,
        data = train.dv[, -1],
        method = "rf",
        trControl = ctrl,
        tuneGrid = rfGrid,
        metric = "ROC",
        ntree = 1500,
        importance = TRUE
    )
    
    saveRDS(rf.dv, "models/rf_dv.Rds")

} else {
    library(randomForest)
    rf.dv <- readRDS("models/rf_dv.Rds")
}
```

```{r}
rf.dv
```

```{r}
pred.rf.dv <- predict(rf.dv, valid.dv[, -1])
confusionMatrix(pred.rf.dv, valid.party)
```

```{r}
vi2 <-varImp(rf.dv)
plot(vi2, top = 30)
```

## Ranger Random Forest

### Grouped Categorical Data

```{r}
d <- train.set
rfGrid <- data.frame(mtry = c(2:9, seq(10, ncol(d) - 2, length.out = 5)))
```

```{r}
if (!file.exists("models/ranger_set.Rds")) {
    set.seed(1056)
    ranger.set <- train(
        Party ~ .,
        data = train.set[, -1],
        method = "ranger",
        trControl = ctrl,
        tuneGrid = rfGrid,
        metric = "ROC",
        num.trees = 1500,
        importance = "impurity"
    )
    
    saveRDS(ranger.set, "models/ranger_set.Rds")

} else {
    library(ranger)
    ranger.set <- readRDS("models/ranger_set.Rds")
}
```
```{r}
ranger.set
```

```{r}
pred.ranger.set <- predict(ranger.set, valid.set[, -1])
confusionMatrix(pred.ranger.set, valid.party)
```

### Independent Categorical Data

```{r}
d <- train.dv
rfGrid <- data.frame(mtry = c(2:9, seq(10, ncol(d) - 2, length.out = 5)))
```

```{r}
if (!file.exists("models/ranger_dv.Rds")) {
    set.seed(1056)
    ranger.dv <- train(
        Party ~ .,
        data = train.dv[, -1],
        method = "ranger",
        trControl = ctrl,
        tuneGrid = rfGrid,
        metric = "ROC",
        num.trees = 1500,
        importance = "impurity"
    )
    
    saveRDS(ranger.dv, "models/ranger_dv.Rds")

} else {
    library(ranger)
    ranger.dv <- readRDS("models/ranger_dv.Rds")
}
```

```{r}
ranger.dv
```

```{r}
pred.ranger.dv <- predict(ranger.dv, valid.dv[, -1])
confusionMatrix(pred.ranger.dv, valid.party)
```

## Parallel Random Forest

### Grouped Categorical Data
```{r}
d <- train.set
rfGrid <- data.frame(mtry = c(2:9, seq(10, ncol(d) - 2, length.out = 5)))
```

```{r}
if (!file.exists("models/prf_set.Rds")) {
    set.seed(1056)
    prf.set <- train(
        Party ~ .,
        data = train.set[, -1],
        method = "parRF",
        trControl = ctrl,
        tuneGrid = rfGrid,
        metric = "ROC",
        ntree = 1500,
        importance = TRUE
    )
    
    saveRDS(prf.set, "models/prf_set.Rds")

} else {
    library(randomForest)
    prf.set <- readRDS("models/prf_set.Rds")
}
```

```{r}
prf.set
```

```{r}
pred.prf.set <- predict(prf.set)
confusionMatrix(pred.prf.set, valid.party)
```

### Independent Categorical Data

```{r}
d <- train.dv
rfGrid <- data.frame(mtry = c(2:9, seq(10, ncol(d) - 2, length.out = 5)))
```

```{r}
if (!file.exists("models/prf_dv.Rds")) {
    set.seed(1056)
    prf.dv <- train(
        Party ~ .,
        data = train.dv[, -1],
        method = "rf",
        trControl = ctrl,
        tuneGrid = rfGrid,
        metric = "ROC",
        ntree = 1500,
        importance = TRUE
    )
    
    saveRDS(prf.dv, "models/prf_dv.Rds")

} else {
    library(randomForest)
    prf.dv <- readRDS("models/prf_dv.Rds")
}
```

```{r}
prf.dv
```

```{r}
pred.prf.dv <- predict(prf.dv, valid.dv[, -1])
confusionMatrix(pred.prf.dv, valid.party)
```

